stages:
- name: build and push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lumen-php-fpm
      pushRemote: true
      registry: reg-k8s.qasir.id:30001
timeout: 60
